const config = require("config");
const discordApiClient = require("./adapters/discordApiClient");
const discordHelper = require("../helpers/discord");
const { memoize, remove } = require("../helpers/cache");
const { DAY, MINUTE, SECOND } = require("../helpers/constants");
const DISCORD_TOKEN = config.get("discord.token");

async function getToken(code) {
  return await discordApiClient.exchangeCode(code);
}

async function refreshToken(refreshToken) {
  return await discordApiClient.refreshToken(refreshToken);
}

async function getCurrentUser(accessToken) {
  return memoize(
    `discord.users.${accessToken}`,
    async () => {
      const user = await discordApiClient.getCurrentUser(`Bearer ${accessToken}`);
      return discordHelper.transformUser(user);
    },
    {
      timeout: DAY,
    },
  );
}

async function getUser(userId) {
  return memoize(
    `discord.users.${userId}`,
    async () => {
      const user = await discordApiClient.getUser(`Bot ${DISCORD_TOKEN}`, userId);
      return discordHelper.transformUser(user);
    },
    {
      timeout: DAY,
    },
  );
}

async function getUserGuilds(accessToken, params) {
  return memoize(
    `discord.users.${accessToken}.guilds`,
    async () => {
      const guilds = await discordApiClient.getCurrentUserGuilds(`Bearer ${accessToken}`, params);
      return guilds.map(discordHelper.transformGuild);
    },
    {
      timeout: MINUTE,
    },
  );
}

async function getGuild(guildId) {
  return memoize(
    `discord.guilds.${guildId}`,
    async () => {
      const guild = await discordApiClient.getGuild(`Bot ${DISCORD_TOKEN}`, guildId);
      return discordHelper.transformGuild(guild);
    },
    {
      timeout: DAY,
    },
  );
}

async function getGuildChannels(guildId) {
  return memoize(
    `discord.guilds.${guildId}.channels`,
    async () => {
      const channels = await discordApiClient.getGuildChannels(`Bot ${DISCORD_TOKEN}`, guildId);
      return channels.map(discordHelper.transformChannel);
    },
    {
      timeout: 30 * SECOND,
    },
  );
}

async function leaveGuild(guildId) {
  await discordApiClient.leaveGuild(`Bot ${DISCORD_TOKEN}`, guildId);
  remove(`discord.botInGuild.${guildId}`);
  remove(`discord.guilds.${guildId}`);
  remove(`discord.guilds.${guildId}.channels`);
  return true;
}

async function isBotInGuild(guildId) {
  return memoize(
    `discord.botInGuild.${guildId}`,
    async () => {
      try {
        await discordApiClient.getGuild(`Bot ${DISCORD_TOKEN}`, guildId);
        return true;
      } catch (error) {
        if (error.response?.status === 404) return false;
        throw error;
      }
    },
    {
      timeout: MINUTE,
    },
  );
}

async function hasBotInGuilds(guildIds = []) {
  const uniqueGuildIds = [...new Set(guildIds)];
  const presence = await Promise.all(uniqueGuildIds.map((guildId) => isBotInGuild(guildId)));

  return Object.fromEntries(uniqueGuildIds.map((guildId, index) => [guildId, presence[index]]));
}

const addMemberRole = (guildId, memberId, roleId, reason) => {
  return discordApiClient.addGuildMemberRole(`Bot ${DISCORD_TOKEN}`, {
    guildId,
    memberId,
    roleId,
    reason,
  });
};

const removeMemberRole = (guildId, memberId, roleId, reason) => {
  return discordApiClient.removeGuildMemberRole(`Bot ${DISCORD_TOKEN}`, {
    guildId,
    memberId,
    roleId,
    reason,
  });
};

const sendMessage = (channelId, payload) => {
  if (!payload) throw new Error("Empty message");

  // If we have files (generated by embeds helper), transform them to attachments
  const files = [];
  if (payload.files && payload.files.length > 0) {
    payload.files.forEach((file, i) => {
      files.push({
        id: i,
        description: file.description,
        filename: file.name,
        image: file.attachment,
      });
    });
    delete payload.files;
    payload.attachments = files.map((file) => ({
      id: file.id,
      description: file.description,
      filename: file.filename,
    }));
  }

  return discordApiClient.createMessage(`Bot ${DISCORD_TOKEN}`, channelId, { payload, files });
};

module.exports = {
  addMemberRole,
  getGuild,
  getGuildChannels,
  getToken,
  getCurrentUser,
  getUser,
  getUserGuilds,
  hasBotInGuilds,
  isBotInGuild,
  leaveGuild,
  refreshToken,
  removeMemberRole,
  sendMessage,
};
